// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: internal/pb/norpn.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchService_GetTask_FullMethodName        = "/norpn.OrchService/GetTask"
	OrchService_SendTaskResult_FullMethodName = "/norpn.OrchService/SendTaskResult"
)

// OrchServiceClient is the client API for OrchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchServiceClient interface {
	GetTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskResponse, error)
	SendTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error)
}

type orchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchServiceClient(cc grpc.ClientConnInterface) OrchServiceClient {
	return &orchServiceClient{cc}
}

func (c *orchServiceClient) GetTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, OrchService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchServiceClient) SendTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchService_SendTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchServiceServer is the server API for OrchService service.
// All implementations must embed UnimplementedOrchServiceServer
// for forward compatibility.
type OrchServiceServer interface {
	GetTask(context.Context, *Empty) (*TaskResponse, error)
	SendTaskResult(context.Context, *TaskResult) (*Empty, error)
	mustEmbedUnimplementedOrchServiceServer()
}

// UnimplementedOrchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchServiceServer struct{}

func (UnimplementedOrchServiceServer) GetTask(context.Context, *Empty) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedOrchServiceServer) SendTaskResult(context.Context, *TaskResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTaskResult not implemented")
}
func (UnimplementedOrchServiceServer) mustEmbedUnimplementedOrchServiceServer() {}
func (UnimplementedOrchServiceServer) testEmbeddedByValue()                     {}

// UnsafeOrchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchServiceServer will
// result in compilation errors.
type UnsafeOrchServiceServer interface {
	mustEmbedUnimplementedOrchServiceServer()
}

func RegisterOrchServiceServer(s grpc.ServiceRegistrar, srv OrchServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchService_ServiceDesc, srv)
}

func _OrchService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchServiceServer).GetTask(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchService_SendTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchServiceServer).SendTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchService_SendTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchServiceServer).SendTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchService_ServiceDesc is the grpc.ServiceDesc for OrchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "norpn.OrchService",
	HandlerType: (*OrchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _OrchService_GetTask_Handler,
		},
		{
			MethodName: "SendTaskResult",
			Handler:    _OrchService_SendTaskResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/norpn.proto",
}
